python:
	sudo apt-get update
	sudo apt-get -y install python3-dev
	sudo apt-get -y install gfortran
	sudo apt-get -y install libopenblas-dev
	sudo apt-get -y install liblapack-dev
	sudo apt-get -y install graphviz
	sudo apt-get -y install python3-pip

libreq:
	sudo pip3 install jupyter

gdal:
	sudo add-apt-repository ppa:nextgis/ppa
	sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev libgdal20 libudunits2-0 libudunits2-dev
	pip3 install gdal


ffmpeg:
	sudo apt-get -y install ffmpeg

